<html>
<style>
body{

  background-color: skyblue;
  text-align: center;
  letter-spacing: 2px;
  font-family: verdana;
  color:white;
}
form{
  background-color: skyblue;
  text-align: center;
  letter-spacing: 2px;
  font-family: verdana;
  color:white;
}
strong{
  font-size: 80px;
}
h1{ margin-bottom: 5%;
  font-size: 30px;

}
input,label{
  text-align: center;

}
</style>

<strong>Contacts Page</strong>

<h1>you are on contact page of <%= qs.name %></h1>

</html>
